name: Dependency Review

on:
  pull_request:
    branches:
      - main
      - staging

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          # Optionally allow specific advisories:
          # allow-ghsas: GHSA-xxxx-xxxx-xxxx
          comment-summary-in-pr: always
